name: Build and Test Betman

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: [1.21]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-dev xorg-dev libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev

    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      run: |
        choco install mingw

    - name: Download dependencies
      run: go mod download

    - name: Run tests
      run: go test ./...

    - name: Build
      run: go build -v ./...

    - name: Build CLI
      run: |
        mkdir -p bin
        go build -o bin/coinflip${{ runner.os == 'Windows' && '.exe' || '' }} main.go

    - name: Build Server
      run: |
        go build -o bin/coinflip-server${{ runner.os == 'Windows' && '.exe' || '' }} main_server.go

    - name: Build GUI (Linux/macOS only)
      if: runner.os != 'Windows'
      run: |
        go build -tags gui -o bin/coinflip-gui${{ runner.os == 'Windows' && '.exe' || '' }} main_gui.go

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: betman-${{ runner.os }}-${{ matrix.go-version }}
        path: bin/